import type { MatchRequest, Player } from "@/types/beta";

export const seedPlayers: Player[] = [
  {
    id: "p1",
    name: "Omar",
    email: "omar@example.com",
    phone: "+201000000001",
    side: "left",
    rating: 1520,
    tier: "Gold",
    placementCount: 2,
    isPlaced: false,
    wins: 2,
    losses: 0,
    confidence: "calibrating",
  },
  {
    id: "p2",
    name: "Karim",
    email: "karim@example.com",
    phone: "+201000000002",
    side: "right",
    rating: 1475,
    tier: "Gold",
    placementCount: 3,
    isPlaced: true,
    wins: 4,
    losses: 2,
    confidence: "stable",
  },
  {
    id: "p3",
    name: "Youssef",
    email: "youssef@example.com",
    phone: "+201000000003",
    side: "both",
    rating: 1640,
    tier: "Platinum",
    placementCount: 3,
    isPlaced: true,
    wins: 5,
    losses: 1,
    confidence: "stable",
  },
  {
    id: "p4",
    name: "Mariam",
    email: "mariam@example.com",
    phone: "+201000000004",
    side: "right",
    rating: 1360,
    tier: "Silver",
    placementCount: 1,
    isPlaced: false,
    wins: 1,
    losses: 1,
    confidence: "calibrating",
  },
];

export const seedMatches: MatchRequest[] = [
  {
    id: "m1",
    location: "Smash Sporting Club",
    scheduledFor: "Today, 8:00 PM",
    status: "open",
    players: ["p1", "p2"],
    minRating: 1300,
    maxRating: 1700,
  },
  {
    id: "m2",
    location: "Alex Padel Hub",
    scheduledFor: "Tomorrow, 7:30 PM",
    status: "open",
    players: ["p3"],
  },
];
